2022-07-12 18:05:50,283 INFO    MainThread:18372 [internal.py:wandb_internal():87] W&B internal server running at pid: 18372, started at: 2022-07-12 18:05:50.283682
2022-07-12 18:05:50,286 INFO    WriterThread:18372 [datastore.py:open_for_write():77] open: G:\yolov7\yolov7\wandb\run-20220712_180548-393n9h6h\run-393n9h6h.wandb
2022-07-12 18:05:50,287 DEBUG   HandlerThread:18372 [handler.py:handle_request():130] handle_request: check_version
2022-07-12 18:05:50,289 DEBUG   SenderThread:18372 [sender.py:send():238] send: header
2022-07-12 18:05:50,289 DEBUG   SenderThread:18372 [sender.py:send_request():252] send_request: check_version
2022-07-12 18:05:50,305 DEBUG   SenderThread:18372 [sender.py:send():238] send: run
2022-07-12 18:05:50,315 INFO    SenderThread:18372 [sender.py:_maybe_setup_resume():505] checking resume status for None/YOLOR/393n9h6h
2022-07-12 18:05:51,305 INFO    WriterThread:18372 [datastore.py:close():281] close: G:\yolov7\yolov7\wandb\run-20220712_180548-393n9h6h\run-393n9h6h.wandb
2022-07-12 18:05:51,305 INFO    HandlerThread:18372 [handler.py:finish():731] shutting down handler
2022-07-12 18:05:51,305 ERROR   MainThread:18372 [internal.py:wandb_internal():158] Thread SenderThread:
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_api.py", line 784, in run_resume_status
    response = self.gql(
  File "D:\Python\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\Python\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_util.py", line 102, in _run
    self._process(record)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal.py", line 291, in _process
    self._sm.send(record)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 240, in send
    send_handler(record)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 678, in send_run
    error = self._maybe_setup_resume(run)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\sender.py", line 508, in _maybe_setup_resume
    resume_status = self._api.run_resume_status(
  File "D:\Python\lib\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "D:\Python\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "D:\Python\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_api.py", line 784, in run_resume_status
    response = self.gql(
  File "D:\Python\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Python\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\Python\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
wandb.errors.CommError: check_hostname requires server_hostname
